plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.asyahir'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'

	// SpringBoot: Lombok
	implementation "org.projectlombok:lombok:1.18.46"
    annotationProcessor "org.projectlombok:lombok:1.18.46"

    // SpringBoot: Webflux
	implementation('org.springframework.boot:spring-boot-starter-webflux')

	//SpringBoot: Kafka
	implementation 'org.springframework.boot:spring-boot-starter-kafka'

	// SpringBoot: MongoDB reactive
	implementation "org.springframework.boot:spring-boot-starter-data-mongodb-reactive"

    // Apache Commons Codec
	implementation 'commons-codec:commons-codec:1.18.0'

	// Apache Commons Lang
	implementation 'org.apache.commons:commons-lang3:3.20.0'

	// Apache Common Collections
	implementation 'org.apache.commons:commons-collections4:4.5.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
